---
- name: install apache software
  hosts: webserver
  become: yes
  tasks:
   - name: install apache software
     apt:
       name: apache2
       state: present
       
   - name: start apache server start
     service:
       name: apache2
       state: started

   - name: Deploy the static website
     copy:
       src: index.html
       dest: /var/www.html
 
