---
- name: install tool on the webserver
  hosts: servers
  become: yes
  tasks:
   - name: install tool on the websever
     apt:
       name: nginx
       state: present

   - name: service start
     service:
       name: nginx
       state: started

   - name: Deploy the static website
     copy:
       src: index.html
       dest: /var/www/html/index.html
 
