---
- name: install tool on the webserver
  hosts: servers
  become: yes
  tasks:
   - name: install tool on the websever
     apt:
       name: nginx
       state: present
     tags:
      - installedngnix

   - name: service start
     service:
       name: nginx
       state: started
     tags:
      - startnginx

   - name: Deploy the static website
     copy:
       src: index.html
       dest: /var/www/html/index.html
       notify: 
         - nginx
  
  handlers:
    - name: Restart the nginx
      service:
        name: nginx
        state: restarted
