---
- name: remove tool on the server
  hosts: servers
  become: yes
  tasks:
   - name: nginx service stopped
     service:
        name: nginx
        state: stopped

   - name: remove tool on the websever
     apt:
       name: nginx
       state: absent

